/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppEmpresasRouteImport } from './routes/_app.empresas'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppCidadesRouteImport } from './routes/_app.cidades'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCidadesRoute = AppCidadesRouteImport.update({
  id: '/cidades',
  path: '/cidades',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cidades': typeof AppCidadesRoute
  '/clientes': typeof AppClientesRoute
  '/empresas': typeof AppEmpresasRoute
}
export interface FileRoutesByTo {
  '/cidades': typeof AppCidadesRoute
  '/clientes': typeof AppClientesRoute
  '/empresas': typeof AppEmpresasRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/cidades': typeof AppCidadesRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cidades' | '/clientes' | '/empresas'
  fileRoutesByTo: FileRoutesByTo
  to: '/cidades' | '/clientes' | '/empresas' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/cidades'
    | '/_app/clientes'
    | '/_app/empresas'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cidades': {
      id: '/_app/cidades'
      path: '/cidades'
      fullPath: '/cidades'
      preLoaderRoute: typeof AppCidadesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCidadesRoute: typeof AppCidadesRoute
  AppClientesRoute: typeof AppClientesRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCidadesRoute: AppCidadesRoute,
  AppClientesRoute: AppClientesRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
